<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/*',
    ];
    /*protected $except = [
        'login',
        'login_mobile',
        'user_modules',
        //'usermodule',
        'user_module_child',
        'usermodulechild',
        'resetPassord',
        'setup/get_restrictions',
        'setup/get_type_current_accounts',
        'setup/get_multiple_current_accounts',
        'setup/get_department',
        'setup/user_data',
        'report/debit2',
        'report/budget',
        'report/ledger',
        'report/checking_balance',
        'report/financial_indicators',
        'report/financial_statements',
        'report/profit_loss_statement',
        'report/personal_account_statement',
        'report/list_personal',
        'report/statement_account',
        'report/statement_account_summary',
        'report/ledge_assinet',
        'report/summary-financial-statement',
        'report/detail-financial-statement',
        'report/financial_analysis_department',
        'report/statement_group_level1',
        'report/statement_group_level2',
        'report/statement_group_level3',
        'report/pdf',
        'report/balance',
        'report/balance_1',
        'report/balance_2',
        'report/balance_activo',
        'report/balance_res_gastos',
        'report/balance_res_ingresos',
        'report/balance_resultados',
        'report/balance_totales',
        'report/statement_group',
        'report/budget_upn',
        'report/pdfbudget_upn',
        'report/pdfbudgetUPN_detail',
        'report/budget_upn_summary',
        'report/budget_main',
        'report/departmental_analysis',
        'report/travels',
        'report/pdftravels',
        'report/travels_summary',
        'report/travels_detail',
        'report/pdftravels_detail',
        'report/travels_detail_total',
        'report/budget_detail',
        'report/budget_detail_total',
        'report/statement_upeu',
        'report/statement_upeu_level',        
        'report/summary_help',
        'report/prevision_social',
        'report/diary_book_summary',
        'report/diary_book',
        'report/payment_ticket',
        'report/quinta_categoria',
        'report/exel',


        //CRUD
        'sale/create_operation',
        'sale/update_operation',
        'sale/delete_operation',
        'sale/run_procedure',
        //CRUD SETUP
        'setup/rol',
        'setup/modulo',
        'setup/modulopost',
        'setup/searchpersona',
        'setup/createuser',
        'setup/assignuserrol',
        'setup/showuserrol',
        'setup/editusuario',
        'setup/userdepto',
        'setup/entitydepto',
        //ACCOUNTING
        'accounting/config-vouchers',
        //'accounting/printing-documents',
        'accounting/printing-documents-details',
        'accounting/vouchers',
        'accounting/config-periodos',
        'accounting/config-periodos-close',
        
        //'accounting/list_config_voucher',
        //'accounting/list_depto_parent',
        //'accounting/config_voucher',
        //'accounting/show_config_voucher',
        //'accounting/update_config_voucher',
        
        //INVENTORY
        'inventory/article',
        //WC
        'cw/estadocuenta',
        'cw/planacademico',
        'cw/useracademico',
        'cw/cargaalumno',
        'cw/cursosalumno',
        'cw/notasalumno', 
        'cw/acceso',
        'cw/datosalumno',
        'cw/datoscontrato',
        'cw/closesession',
        'cw/datosalumnovisa',
        'cw/verprorroga',
        'cw/alerta',
        //Mobile
        'mobile/login',
        'mobile/forget_password',
        'mobile/user_data',
        'mobile/st_data',
        'mobile/st_data_items',
        'mobile/st_data_details',
        'mobile/dep_data',
        'mobile/dep_data_items',
        'mobile/dep_data_details',
        'mobile/tra_data',
        'mobile/tra_data_details',
        'mobile/persons',
        'mobile/st_data_salary_ingresos',
        'mobile/st_data_salary_descuentos',
        'mobile/persons_year',
        'mobile/persons_directory',
        'mobile/persons_directory_search',
        'mobile/financial_graphs_datagraph',
        'mobile/financial_graphs_datagraph_options',
        'mobile/version_validate',
        'mobile/profile_worker',
        'mobile/account_statement_salary_receipts_detail',
        'mobile/account_statement_salary_discounts_detail'
    ];*/
}
